[tool.poetry]
name = "atguigu24"
version = "0.1.0"
description = ""
authors = ["YS-desktop <yangoo6910@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
wxpython = "^4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
